

```{r , include=FALSE}
#tutorial::go_interactive(greedy = TRUE)
knitr::opts_chunk$set(echo = TRUE,error=TRUE)
```

# REAL-WORLD APPLICATIONS AND CASE STUDIES (CODE CHALLENGES)

The following exercises will test your understanding of the material covered during this course. Each exercise corresponds to material covered in each section of the Introduction to R manual. It’s entirely up to you how you progress through these exercises, everyone learns at their own pace and in their own way. You can either work your way through each section of the manual and then test your understanding of the material by completing the associated exercise. Alternatively, you can start with each exercise and refer back to the appropriate material in the manual. Or find another way that works for you. Whichever approach you use, make sure that you write your R code in RStudio (or your favourite script editor), annotate it liberally and save it regularly.


## 1. Base R 

Download the answers template via the link [Base R Answers Template](https://github.com/balsaedi/-R-Visualization/raw/main/Base%20R%20Answer%20Template.R).

i. create a new variable called `my.num` that contains 6 numbers; 5,4,7,8,12,14
ii. multiply `my.num` by 4
iii. create a second variable called `my.char` that contains 5 character strings; Robert, Parker, Robert, Robert, Parker
iv. combine the two variables `my.num` and `my.char` into a variable called `both`
v. what is the length of `both`?
vi. what class is `both`?
vii. divide `both` by 3, what happens?
viii. create a vector with elements 1 2 3 4 5 6 and call it `x`
ix. create another vector with elements 10 20 30 40 50 and call it `y`
x. what happens if you try to add `x` and `y` together? why?
xi. append the value 60 onto the vector y (hint: you can use the c() function) add `x` and `y` together
xiii. multiply `x` and `y` together. pay attention to how R performs operations on vectors of the same length.



## 2. Functions

Download the answers template for this code challenge via the link [Functions Answers Template](https://github.com/balsaedi/-R-Visualization/raw/main/Functions%20Answer%20Template.R).


a. Write a function, `sqdif`, that does the following:

  i. takes two numbers `x`  and `y` with default values of 2 and 3.
  ii. takes the difference
  iii. squares this difference
  iv. then returns the final value
   v. checks that `x` and `y` are numeric and `stop` S with an error message otherwise
  
b. Try to write a function called `top()` that takes a `matrix` or `data.frame` and a number `n`, and returns the first n rows and columns, with the default value of `n=5`. What do you get when you run the following code?:

i. `top(matrix(1:100, ncol=10))`

ii. `top(matrix(1:25, ncol = 5), 2)`

 
c. Write a function called `my_t_CI` that will calculate a 95% one sample t interval. The results will be stored in a list to be returned containing sample mean and the confidence interval. The input to the functions is the numeric vector containing our data. For review, the formula for a 95% one sample t interval is  

$$
\bar{x} \pm 1.96*s/\sqrt{n}
$$
i. Generate random numbers from a normal distribution with the seed `set.seed(60)` and code `data_sim = rnorm(100)`. 

ii. What do you get when you run `my_t_CI(data_sim)`?

iii. Compare the accuracy of your function with the built-in function 
`t.test(data_sim)`. What do you find?




## 3. Data Visualization with Base R

Download the answers template via the link [Base R Visualization Answers Template](https://github.com/balsaedi/-R-Visualization/raw/main/Base%20R%20Visualization%20Answers%20Template.R).


i. Download the data file  `squid1.xlsx`  from [Squid Data](https://github.com/balsaedi/-R-Visualization/blob/main/squid1.xlsx) link and save it to your working directory. Open this file in Microsoft Excel and save it as a tab delimited file type. Name the file `squid1.txt` and save it to the working directory.
These data were originally collected as part of a study published in Aquatic Living Resources1 in 2005. The aim of the study was to investigate the seasonal patterns of investment in somatic and reproductive tissues in the long finned squid Loligo forbesi caught in Scottish waters. Squid were caught monthly from December 1989 - July 1991 (`month` and `year` variables). After capture, each squid was given a unique `specimen` code, weighed (`weight`) and the sex determined (`sex` - only female squid are included here). The size of individuals was also measured as the dorsal mantle length (`DML`) and the mantle weight measured without internal organs (`eviscerate.weight`). The gonads were weighed (`ovary.weight`) along with the accessory reproductive organ (the nidamental gland, `nid.weight`, `nid.length`). Each individual was also assigned a categorical measure of maturity (`maturity.stage`, ranging from 1 to 5 with 1 = immature, 5 = mature). The digestive gland weight (`dig.weight`) was also recorded to assess nutritional status of the individual.

ii. Import the ‘squid1.txt’ file into R using the read.table() function and assign it to a variable named squid. Use the `str()` function to display the structure of the dataset and the `summary()` function to summarise the dataset. How many observations are in this dataset? How many variables? The `year`, `month` and `maturity.stage` variables were coded as integers in the original dataset. Here we would like to code them as factors. Create a new variable for each of these variables in the `squid` dataframe and recode them as factors. Use the `str()` function again to check the coding of these new variables.


iii. How many observations are there per month and year combination (hint: remember the `table()` or `xtabs()` functions?)? Don’t forget to use the factor recoded versions of these variables. Do you have data for each month in each year? Which years have the most observations? (optional) Use a combination of the `xtabs()` and `ftable()` functions to create a flattened table of the number of observations for each year, maturity stage and month (aka a contingency table).


iv. The humble cleveland dotplot is a great way of identifying if you have potential outliers in continuous variables. Create dotplots (using the `dotchart()` function) for the following variables; `DML`, `weight`, `nid.length` and `ovary.weight`. Do these variables contain any unusually large or small observations? Don’t forget, if you prefer to create a single figure with all 4 plots you can always split your plotting device into 2 rows and 2 columns . Use the `pdf()` function to save a pdf version of your plot(s) in your output directory you created . You may also include some alternative code in the solutions for this exercise using the `dotplot()` function from the `lattice` package.


v. It looks like the variable `nid.length` contains an unusually large value. Actually, this value is biologically implausible and clearly an error. The researchers were asked to go back and check their field notebooks and sure enough they discover a typo. It looks like a tired researcher accidentally inserted a zero by mistake when transcribing these data (mistakes in data are very common and why we __always__ explore, check and validate any data we are working on). We can clearly see this value is over 400 so we can use the `which()` function to identify which observation this is `which(squid$nid.length > 400)`. It looks like this is the 11th observation of the `nid.length` variable. Use your skill with the square brackets `[ ]` to first confirm the this is the correct value (you should get 430.2) and then change this value to 43.2. Now redo the dotchart to visualise your correction. Caution: You can only do this because you have confirmed that this is an transcribing error. You should not remove or change values in your data just because you feel like it or they look ‘unusual’. This is scientific fraud! Also, the advantage of making this change in your R script rather than in Excel is that you now have a permanent record of the change you made and can state a clear reason for the change.


vi. When exploring your data it is often useful to visualise the distribution of continuous variables. Take a look at the histogram section of this manual  and then create histograms for the variables; `DML`, `weight`, `eviscerate.weight` and `ovary.weight`. Again, its up to you if you want to plot all 4 plots separately or in the same figure. Export your plot(s) as pdf file(s) to the `output` directory. One potential problem with histograms is that the distribution of data can look quite different depending on the number of ‘breaks’ used. The `hist()` function does it’s best to create appropriate ‘breaks’ for your plots (it uses the `Sturges algorithm` for those that want to know) but experiment with changing the number of breaks for the `DML` variable to see how the shape of the distribution changes.


vii. Scatterplots are great for visualising relationships between two continuous variables. Plot the relationship between `DML` on the x axis and `weight` on the y axis. How would you describe this relationship? Is it linear? One approach to linearising relationships is to apply a transformation on one or both variables. Try transforming the `weight` variable with either a natural log (`log()`) or square root (`sqrt()`) transformation. I suggest you create new variables in the `squid` dataframe for your transformed variables and use these variables when creating your new plots . Which transformation best linearises this relationship? Again, save your plots as a pdf file (or try saving in your output directory as jpeg or png format using the jpeg() or png() functions.


viii. When visualising differences in a continuous variable between levels of a factor (categorical variable) then a `boxplot` is your best friend (avoid using bar plots - Google ‘bar plots are evil’ for more info). Create a boxplot to visualise the differences in `DML` at each maturity stage (don’t forget to use the recoded version of this variable you created earlier in __ii__) . Include x and y axes labels in your plot. An alternative to the boxplot is the `violin` plot. A violin plot is a combination of a boxplot and a `kernel` density plot and is great at visualising the distribution of a variable. To create a violin plot you will first need to install the `vioplot` package from CRAN and make it available using library(vioplot). You can now use the `vioplot()` function in pretty much the same way as you created your boxplot.


ix. To visualise the relationship between two continuous variables but for different levels of a factor variable you can create a conditional scatterplot. Use the `coplot()` function  to plot the relationship between `DML` on the x axis and square root transformed `weight` on the y axis (you created this variable in __vi__) for each level of maturity stage. Does the relationship between `DML` and `weight` look different for each maturity stage (suggesting an interaction)? If you prefer, you can also create a similar plot using the `xyplot()` function  from the `lattice` package.


x. To explore the relationships between multiple continuous variables it’s hard to beat a pairs plot. Create a pairs plot for the variables; `DML`, `weight`, `eviscerate.weight`, `ovary.weight`, `nid.length`, and `nid.weight`. If it looks a little cramped in RStudio then click on the ‘zoom’ button in the plot viewer to see a larger version. One of the great things about the `pairs()` function is that you can customise what goes into each panel. Modify your pairs plot to include a histogram of the variables on the diagonal panel and include a correlation coefficient for each relationship on the upper triangle panels. Also include a smoother (wiggly line) in the lower triangle panels to help visualise these relationships. 

xi. Almost every aspect of the figures you create in R is customizable. Learning how to get your plot looking just right is not only rewarding but also means that you will never have to include a plot in your paper/thesis that you’re not completely happy with. When you start learning how to use R it can sometimes seem to take a lot of work to customize your plots. Don’t worry, it gets easier with experience (most of the time anyway) and you will always have your code if you want to create a similar plot in the future. Use the `plot()` function to produce a `scatterplot` of `DML` on the x axis and `ovary weight` on the y axis (you might need to apply a transformation on the variable `ovary.weight`). Use a different `colour` to highlight points for each level of maturity stage. Produce a `legend` explaining the different colours and place it in a suitable position on the plot. Format the graph further to make it suitable for inclusion into your paper/thesis (i.e. add axes labels, change the axes scales etc).




## 4. Data Visualization with ggplot2

These exercises require you to generate plots of various kinds. This document
shows both the plots that you should obtain and the solutions. Click on the [Data Visualization with ggplot2 Answers Template](https://github.com/balsaedi/-R-Visualization/raw/main/ggplot2%20Visualization%20Answers%20Template.R) to download the answers template to answer all the questions to this code challenge.



### Part I -- geoms and aesthetics

These first few exercises will run through some of the simple principles of
creating a ggplot2 object, assigning aesthetics mappings and geoms.

1. Read in the cleaned [patients](https://github.com/balsaedi/-R-Visualization/raw/main/patient-data.txt) dataset, `patient-data-cleaned.txt`, into a new object called `patients` using `read_tsv()` function.

### Scatterplots

2. Generate a scatterplot of BMI versus Weight using the patient dataset and add
   a colour scale based on the Height variable.


3. Using an additional geom, add an extra layer of a fit line to the previous plot.


4. Does the fit in the previous plot look good? Look at the help page for
   `geom_smooth` and adjust the method to fit a straight line without standard
   error bounds.


### Boxplots and Violin plots

5. Generate a boxplot of Score values comparing smokers and non-smokers.


6. Split the previous boxplot into male and female groups with different colours.


7. Produce a similar boxplot of Scores but this time group data by Sex and colour
   the interior of the box (not the outline) by Age. Change this plot to a violin
   plot.

**Note**: Having loaded the data using `read_tsv`, the `Age` column has been 
set to `dbl` (short for `double`, a `numeric` vector type) as it only contains
numbers. This makes it a **continuous** variable. In order to split the boxplot
by age and colour each one according to Age, it is necessary to change age to 
be a **categorical** variable. We can do this by changing the `Age` column into a
different vector type: a `factor`. 


### Histogram and Density plots

8. Generate a histogram of BMIs with each bar coloured blue, choosing a
    suitable bin width.

9. Instead of a histogram, generate a density plot of BMI


10. Generate density plots of BMIs coloured by Sex.

_Hint: alpha can be used to control transparency._


### Part II - facets

In this next part you will create plots with faceting. First check that the cleaned
patients dataset has been read in and is available as a data frame in your current
session. If you haven't done so, convert the Age variable to a factor.

11. Using the patient dataset generate a scatterplot of BMI versus Weight, add a colour scale to the scatterplot based on the Height variable, and split the plot into a grid of plots separated by Smoking status and Sex.


12. Generate a boxplot of BMIs comparing smokers and non-smokers, colour boxplot
    by Sex, and include a separate facet for people of different age.

13. Produce a similar boxplot of BMIs but this time group data by Sex, colour by Age and facet by Smoking status.


### Part III -- scales and themes

In these exercises we look at adjusting the scales and themes of our plots.

Check that the cleaned patients dataset has been read in and is available as a data
frame in your current session. Check also that the Age variable is a factor.

### Scales

14. Generate a scatterplot of BMI versus Weight from the patients dataset.


15. Starting from the previous plot, adjust the BMI axis to show only labels for 20, 30, 40 and the weight axis to show breaks for 60 to 100 in steps of 5, adding the units (kilograms) to the axis label.


16. Create a violin plot of BMI by Age where violins are filled using a sequential
    colour palette.


17. Create a scatterplot of BMI versus Weight and add a continuous colour scale for
    the height. Make the colour scale  with a midpoint (set to mean point) colour of grey and extremes of green (low) and red (high).


### Themes

18. Recreate the scatter plot of BMI by weight this time colouring by age group and add a straight line fit (but no standard error/confidence intervals) for each age group.


19. Remove the legend title from the previous plot, change the background colours of legend keys to white and place the legend at the bottom of the plot.


20. Add a title to the plot and remove the minor grid lines.
    Save the plot to a 7 by 7 inch image file.


## 5. Data Visualization using ggplot2 Part II 

Access the answers template [here](https://github.com/balsaedi/-R-Visualization/raw/main/ggplot2%20Part%20II%20Visualization%20Answers%20Template.R) to answer all the questions.

i. Plot a `sin(x)/x` using `ggplot()` function.

Hint: Trigonometric functions in R use angles in radians (see ? sin). 2 times pi is 360 degrees.

ii. The ‘cars’ data set gives the speed of cars and the distances taken to stop. Note that the data were recorded in the 1920s. Plot the ‘cars’ data set as a scatter plot. Plot all data points with distances taken to stop greater than 80 in red.

- basic version with points

- Add color as a mapping that is only used by geom_points

- define the colors using a manual color scale

- add a second geom that produces a smoothed line (default is a local polynomial regression)



